version: '3'
services:
  node:
    container_name: back_documents_manager
    restart: always
    build: ./back
    ports:
      - "3009:3009"
    links:
      - mongo
    volumes:
        - .:/usr/src/app
        - gestordoc:/storage/gestordoc/files
volumes:
  gestordoc:
