version: '3'
services:
  react:
    container_name: front_documents_manager
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '3009:3000'
    links:
      - node
  node:
    container_name: back_documents_manager
    restart: always
    build: ./back
    ports:
      - "8080:8080"
    links:
      - mongo
    volumes:
        - .:/usr/src/app
  mongo:
    container_name: db_documents_manager
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_documents_manager:/data/db
volumes:
  db_documents_manager: