version: '3'
services:
  react:
    container_name: front-documents-manager-docker-container
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '3009:3000'
    links:
      - node
  node:
    container_name: back-documents-manager
    restart: always
    build: ./back
    ports:
      - "8080:8080"
    links:
      - mongo
    volumes:
        - .:/usr/src/app
  mongo:
    container_name: db-documents-manager
    image: mongo
    ports:
      - "27017:27017"