version: '3'
services:
  node:
    container_name: back_documents_manager
    restart: always
    build: ./back
    ports:
      - "3009:3009"
    links:
      - mongo
    volumes:
        - .:/usr/src/app
        - gestordoc:/storage/gestordoc/files
  mongo:
    container_name: db_documents_manager
    image: mongo
    ports:
      - "27018:27018"
    volumes:
      - db_documents_manager:/data/db
volumes:
  db_documents_manager:
  gestordoc: