version: '3'
services:
  node:
    container_name: back_documents_manager
    restart: always
    build: ./back
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
        - .:/usr/src/app
  mongo:
    container_name: db_documents_manager
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_documents_manager:/data/db
volumes:
  db_documents_manager: