version: '3'
services:
  node:
    container_name: backend-documents-manager-docker-container
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
    volumes:
        - .:/usr/src/app
  mongo:
    container_name: database-documents-manager-docker-container
    image: mongo
    ports:
      - "27017:27017"